spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:blog-search
    driver-class-name: org.h2.Driver
    username: sa
    password:

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb