spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:blog-search
    driver-class-name: org.h2.Driver
    username: sa
    password:
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
      url: https://dapi.kakao.com/v2/search/blog

naver:
  rest:
    api:
      client-id: ${NAVER_REST_API_CLIENT_ID}
      client-secret: ${NAVER_REST_API_CLIENT_SECRET}
      url: https://openapi.naver.com/v1/search/blog.json

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
      url: https://dapi.kakao.com/v2/search/blog

naver:
  rest:
    api:
      client-id: ${NAVER_REST_API_CLIENT_ID}
      client-secret: ${NAVER_REST_API_CLIENT_SECRET}
      url: https://openapi.naver.com/v1/search/blog.json